package com.arcos.gestion_ordenes.GUI.views;

import com.arcos.gestion_ordenes.DAO.DAOOrdenTrabajoImpl;
import com.arcos.gestion_ordenes.DAO.DAOOrden_MaterialImpl;
import com.arcos.gestion_ordenes.DAO.DAOOrden_TrabajosImpl;
import com.arcos.gestion_ordenes.DAO.DAOTecnicosImpl;
import com.arcos.gestion_ordenes.DAOinter.DAO;
import com.arcos.gestion_ordenes.DAOinter.DAOOrden;
import com.arcos.gestion_ordenes.DAOinter.DAOTecnico;
import com.arcos.gestion_ordenes.GUI.DashBoard;
import com.arcos.gestion_ordenes.Logica.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;


public class verOrdenes extends javax.swing.JPanel {

    DAOOrden dOrdenTrabajo = new DAOOrdenTrabajoImpl();
    DAO dOrden_Material = new DAOOrden_MaterialImpl();
    DAO dOrden_Trabajos = new DAOOrden_TrabajosImpl();
    DAOTecnico dTecnico=new DAOTecnicosImpl();
    List<Tecnico>lTecnicos=null;
    List<OrdenTrabajo> lOrdenTrabajo = null;
    List<Orden_Material> lOrden_material = null;
    List<Orden_Trabajos> lOrden_trabajos = null;

    public verOrdenes() {
        initComponents();
        cargarTabla();
    }

    public void init() {
        labelMain.putClientProperty("FlatLaf.style", "font: bold $h1.regular.font");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelMain = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableOrdenes = new javax.swing.JTable();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(680, 440));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(680, 440));

        labelMain.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelMain.setForeground(new java.awt.Color(0, 0, 0));
        labelMain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMain.setText("Ordenes Gases S.A");

        tableOrdenes.setBackground(new java.awt.Color(255, 255, 204));
        tableOrdenes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tableOrdenes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableOrdenes);

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lupa.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/borrar (1).png"))); // NOI18N
        btnBorrar.setText("Borrar");
        btnBorrar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBorrar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/editar.png"))); // NOI18N
        btnEditar.setText("Ver/Editar");
        btnEditar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnEditar.setIconTextGap(2);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(labelMain, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(113, 113, 113)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnBuscar)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnEditar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnBorrar))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(labelMain, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBorrar)
                    .addComponent(btnEditar))
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 819, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    //<editor-fold defaultstate="collapsed" desc="Codigo de los botones">
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if(tableOrdenes.getRowCount()>0 && tableOrdenes.getSelectedRow()!=-1){
            int id_orden=Integer.parseInt(String.valueOf(tableOrdenes.getValueAt(tableOrdenes.getSelectedRow(), 0)));
            DashBoard.setPanel(new Ver_editar_orden(id_orden));
            
        }
        
        else{
             javax.swing.JOptionPane.showMessageDialog(this, "No ha seleccionado ningun registro. \n", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        if(tableOrdenes.getRowCount()>0 && tableOrdenes.getSelectedRow()!=-1){
            int id_orden=Integer.parseInt(String.valueOf(tableOrdenes.getValueAt(tableOrdenes.getSelectedRow(),0)));
            DefaultTableModel tableModel=(DefaultTableModel) tableOrdenes.getModel();
            tableModel.removeRow(tableOrdenes.getSelectedRow());
            try {
                dOrden_Material.eliminar(id_orden);
                dOrden_Trabajos.eliminar(id_orden);
                dOrdenTrabajo.eliminar(id_orden);
                
                javax.swing.JOptionPane.showMessageDialog(this, "Orden eliminada con exito. \n", "Orden Eliminada", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex) {
                Logger.getLogger(verOrdenes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            javax.swing.JOptionPane.showMessageDialog(this, "No ha seleccionado ningun registro. \n", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBorrarActionPerformed
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Modelado de tabla">
    private DefaultTableModel cargarTabla() {
        DefaultTableModel tModel=modelarTabla();
        try {
            lOrdenTrabajo = dOrdenTrabajo.traerTodos();
            lTecnicos = dTecnico.traerTodos();

            for (OrdenTrabajo ot : lOrdenTrabajo) {
                Tecnico tec=lTecnicos.stream().filter(t->t.getId_tecnico()==ot.getId_tecnico()).findFirst().orElse(null);
                if (tec != null) {
                    Object[] rows = {ot.getId_orden(), ot.getFecha(), ot.getTotal(), ot.getId_solicitud(), tec.getNombre()+" "+tec.getApellido(), ot.isEstado()};
                    tModel.addRow(rows);
                    tableOrdenes.setModel(tModel);
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(verOrdenes.class.getName()).log(Level.SEVERE, null, ex);
        }
         return tModel;
    }

    public DefaultTableModel modelarTabla(){
                DefaultTableModel tModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        String[] columnas = {"N.Orden", "Fecha", "Total", "n.Solicitud", "Tecnico", "Estado"};
        tModel.setColumnIdentifiers(columnas);
        return tModel;
    }
    //</editor-fold>
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelMain;
    private javax.swing.JTable tableOrdenes;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables

}
